### PR TITLE
For #37. Api products/tags remove depends on since products/tags could be managed separately 

### PR DESCRIPTION
**Pull request by levimatheri**
For #37. Remove products `dependsOn` on products-apis resource since products could be managed separately. This is the behavior in azure-api-management-devops-toolkit, see [here](https://github.com/Azure/azure-api-management-devops-resource-kit/blob/a993488b807459713ee991e36cfbbd5d2f340d42/src/ArmTemplates/Creator/TemplateCreators/ProductAPITemplateCreator.cs#L47)

### CODE REVIEW

**Comment by levimatheri** [comment]
@mirsaeedi Please review

**Comment by mirsaeedi** [comment]
Thanks for the PR @levimatheri. 

For the `Products` and `Tags` that are still in the yml, we should keep the `dependsOn` relationship. So, I think we should make the following changes:

1. in `ApiDeploymentDefinition.Dependencies()`, we should include only products that are defined in the yml. I'm thinking something along the lines of:

```C#
var dependentProducts = ProductList // list of products in the API definition
	.Where(product => Root.Products.Any(p => GetProductName(product) == p.Name)) // filters out products that are not in the yml
	.Select(product => $"[resourceId('{ResourceType.Product}', parameters('ApimServiceName'), '{GetProductName(product)}')]");
```

2. In `ApiResourceCreator.CreateProductApis()`, we should add the product name to the `dependsOn` list, only when the product is defined in the yml. So, instead of removing that line, I'm thinking of the following:

```C#
var dependencies = new List<string>()
{
        $"[resourceId('{ResourceType.Api}', parameters('ApimServiceName'), '{apiDeploymentDefinition.Name}')]",
};

var productName = apiDeploymentDefinition.GetProductName(productDisplayName);
if (apiDeploymentDefinition.Root.Products.Any(product => product.Name == productName))
{
         dependencies.Add($"[resourceId('{ResourceType.Product}', parameters('ApimServiceName'), '{productName}')]");
}
```

**Comment by levimatheri** [comment]
@mirsaeedi Thanks for the feedback. I've updated the PR with your suggestion, tested it and it works. Please review :) 

Also question, do we want to update the ApiVersions for the schemas? I see they are up to [2021-08-01](https://docs.microsoft.com/en-us/azure/templates/microsoft.apimanagement/2021-08-01/service/apis?tabs=json)

**Comment by mirsaeedi** [comment]
closes #37

**Pull request merged**
