### PR TITLE
Fixed an error while generating Backend ARM Template

### PR DESCRIPTION
**Pull request by nvmathure**

### CODE REVIEW

**Comment by nvmathure** [comment]
This pull request closes Issue #10

**Comment by mirsaeedi** [comment]
Thanks for your contribution. I'll merge the code once I have branch [refactoring-v1](https://github.com/mirsaeedi/dotnet-apim/tree/refactoring-v1) merged into the `master` branch. It will be this week hopefully.

**Comment by mirsaeedi** [comment]
Hi @nvmathure 

I highly appreciate your time for this contribution. As the project has undergone major changes, I should abandon this PR. In the new version, the issue is fixed with backend entities. 

Can you please explain what the purpose of `NamedValues` is in your change? Thanks :)

**Comment by nvmathure** [comment]
Hi,

NamedValues will add values to "Named values"
image

image

Thanks

Nandan Mathure

**Comment by andrewdmoreno** [comment]
@mirsaeedi - This feature is also useful if you don't want a secret variable to be visible inside of your policy while using the variable replacement feature. You would instead create it as a named variable and then the policy would reference the named value. 

This is also one of the reasons I proposed #5 . If you wanted to use a secret you could pass it in as a secret in arm parameters, and use it to create a secret named value arm resource. Then the value would not visible in plain text in the generated deployment template file. Let me know if that makes sense, otherwise I can explain more.

**Pull request closed without merging**
